### ISSUE TITLE
Compare to gatsby-source-google-analytics-reporting-api

### ISSUE THREAD

**Issue by Vacilando** [Kornil/gatsby-plugin-google-analytics-reporter#1]
I see there's another plugin with similar purpose at https://www.gatsbyjs.org/packages/gatsby-source-google-analytics-reporting-api/ (https://github.com/antonmedv/gatsby-source-google-analytics-reporting-api). 

The other project has been inactive for 2 years.

Is your project https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics-reporter/ (https://github.com/Kornil/gatsby-plugin-google-analytics-reporter) an improvement over the old one — or are they totally unrelated? 

Any plans to join forces with the other project, or is there no reason to do so?

**Comment by Kornil** [comment]
This project uses the new Analytics Reporting v4 API, while the one you linked uses V3 and as you said, wasn't touched in the last 2 years.

My purpose in making this project was to have something reliable (since I need it for my own blog at https://decodenatura.com/popular/) and using the latest and better supported V4 API. Google has a history of dropping projects so I wanted to make sure I'd not have to redo all this when V3 support will stop.

I have not spoken with the creator of the other project so I don't know his/her intentions regarding the project. I intend to continue supporting this library as a thank you to the generous gatsby community and because I also need it myself :)
